import bcrypt from "bcryptjs"
import mongoose, { Types } from "mongoose"

import connectDB from "../config/db"
import Assignment from "../models/Assignment"
import Attendance, { AttendanceDocument } from "../models/Attendance"
import College from "../models/College"
import Course, { Topic } from "../models/Course"
import Department from "../models/Department"
import Grade, { IGrade } from "../models/Grade"
import JobPosting, { JobPostingDocument } from "../models/JobPosting"
import Semester from "../models/Semester"
import User, { UserRole } from "../models/user"
